"""Add vehicle_number to Booking

Revision ID: ee0fb053901e
Revises: adf7ec90f000
Create Date: 2025-07-28 17:54:15.247176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee0fb053901e'
down_revision = 'adf7ec90f000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_number', sa.String(length=20), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=20), nullable=True))

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_column('vehicle_number')

    # ### end Alembic commands ###
